# Generated by Django 6.0.8 on 2026-08-17 05:28

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'parameter category',
                'verbose_name_plural': 'parameter categories',
                'ordering': ('sort_order', 'name'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='uq_parameter_category_code_ci'), models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='ck_parameter_category_code_set')],
            },
        ),
        migrations.CreateModel(
            name='ParameterDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service', models.SlugField(max_length=64)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('url', 'URL'), ('json', 'JSON')], max_length=16)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('database', 'Database'), ('env', 'Environment'), ('default', 'Default')], default='database', max_length=16)),
                ('is_secret', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('requires_restart', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='control.parametercategory')),
            ],
            options={
                'ordering': ('category__sort_order', 'sort_order', 'service', 'key'),
            },
        ),
        migrations.CreateModel(
            name='ParameterChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], db_index=True, max_length=16)),
                ('revision', models.PositiveBigIntegerField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_changes', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='control.parameterdefinition')),
            ],
            options={
                'ordering': ('-changed_at', '-revision'),
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], db_index=True, max_length=16)),
                ('value', models.JSONField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='control.parameterdefinition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_parameter_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('definition__service', 'definition__key', 'environment'),
            },
        ),
        migrations.AddConstraint(
            model_name='parameterdefinition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('service'), django.db.models.functions.text.Lower('key'), name='uq_parameter_definition_service_key_ci'),
        ),
        migrations.AddConstraint(
            model_name='parameterdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('service', ''), _negated=True), name='ck_parameter_definition_service_set'),
        ),
        migrations.AddConstraint(
            model_name='parameterdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('key', ''), _negated=True), name='ck_parameter_definition_key_set'),
        ),
        migrations.AddConstraint(
            model_name='parameterdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('is_secret', False), ('source', 'env'), _connector='OR'), name='ck_parameter_secret_uses_env'),
        ),
        migrations.AddIndex(
            model_name='parameterchange',
            index=models.Index(fields=['definition', 'environment', '-changed_at'], name='control_chg_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='parameterchange',
            constraint=models.UniqueConstraint(fields=('definition', 'environment', 'revision'), name='uq_parameter_change_revision'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(fields=('definition', 'environment'), name='uq_parameter_value_definition_env'),
        ),
    ]
