# Generated by Django 6.0.8 on 2026-08-17 13:01

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('admin', 'Administrator')], db_index=True, max_length=16)),
                ('key_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('hash_algorithm', models.CharField(default='sha256', editable=False, max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_credentials', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_api_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('environment', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MailAgentPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mailboxes', models.JSONField(default=list)),
                ('permissions', models.JSONField(default=list)),
                ('recipient_domains', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_policy', to='control.apicredential')),
            ],
            options={
                'verbose_name': 'mail agent policy',
                'verbose_name_plural': 'mail agent policies',
                'ordering': ('credential__environment', 'credential__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='apicredential',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('environment'), name='uq_api_credential_name_env_ci'),
        ),
        migrations.AddConstraint(
            model_name='apicredential',
            constraint=models.CheckConstraint(condition=models.Q(('key_id', ''), _negated=True), name='ck_api_credential_key_id_set'),
        ),
        migrations.AddConstraint(
            model_name='apicredential',
            constraint=models.CheckConstraint(condition=models.Q(('key_hash', ''), _negated=True), name='ck_api_credential_hash_set'),
        ),
    ]
