# Generated by Django 6.0.8 on 2026-08-17 13:47

from django.db import migrations, models


def assign_mail_scope(apps, schema_editor):
    ApiCredential = apps.get_model('control', 'ApiCredential')
    ApiCredential.objects.all().update(scopes=['mail.api'])


def clear_scopes(apps, schema_editor):
    ApiCredential = apps.get_model('control', 'ApiCredential')
    ApiCredential.objects.all().update(scopes=[])


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_apicredential_mailagentpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='scopes',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(assign_mail_scope, clear_scopes),
        migrations.AlterField(
            model_name='apicredential',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('agent', 'Agent'), ('admin', 'Administrator')], db_index=True, max_length=16),
        ),
    ]
