# Generated by Django 6.0.8 on 2026-08-18 10:59

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


SCOPE_DEFINITIONS = {
    'mail.api': ('Mail API', 'Use the Microsoft Graph mail API.'),
    'sql.query': ('SQL queries (legacy)', 'Legacy SQL query scope kept during migration.'),
    'sql.catalog.read': ('Read SQL catalog', 'List SQL queries allowed by access profiles.'),
    'sql.query.execute': ('Execute SQL queries', 'Execute published SQL queries allowed by access profiles.'),
    'sql.query.upload': ('Upload SQL queries', 'Upload arbitrary SQL text. Reserved for trusted maintainers.'),
    'voice.transcribe': ('Voice transcription', 'Transcribe voice recordings.'),
    'diarization.run': ('Diarization', 'Run speaker diarization.'),
}

ROLE_DEFINITIONS = {
    'mail-agent': ('Mail agent', ('mail.api',)),
    'sql-consumer': (
        'SQL consumer',
        ('sql.query', 'sql.catalog.read', 'sql.query.execute'),
    ),
    'sql-maintainer': (
        'SQL maintainer',
        ('sql.query', 'sql.catalog.read', 'sql.query.execute', 'sql.query.upload'),
    ),
    'voice-client': ('Voice client', ('voice.transcribe',)),
    'diarization-client': ('Diarization client', ('diarization.run',)),
}

LEGACY_SCOPE_ROLES = {
    'mail.api': 'mail-agent',
    'sql.query': 'sql-consumer',
    'voice.transcribe': 'voice-client',
    'diarization.run': 'diarization-client',
}


def migrate_scopes_to_roles(apps, schema_editor):
    ApiCredential = apps.get_model('control', 'ApiCredential')
    ApiCredentialRole = apps.get_model('control', 'ApiCredentialRole')
    ApiScope = apps.get_model('control', 'ApiScope')
    AccessRole = apps.get_model('control', 'AccessRole')
    AccessRoleScope = apps.get_model('control', 'AccessRoleScope')

    scopes = {}
    for code, (name, description) in SCOPE_DEFINITIONS.items():
        scope, _created = ApiScope.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'description': description,
                'is_active': True,
            },
        )
        scopes[code] = scope

    roles = {}
    for code, (name, scope_codes) in ROLE_DEFINITIONS.items():
        role, _created = AccessRole.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'description': f'Standard access role: {name}.',
                'is_active': True,
            },
        )
        roles[code] = role
        for scope_code in scope_codes:
            AccessRoleScope.objects.get_or_create(
                role=role,
                scope=scopes[scope_code],
            )

    for credential in ApiCredential.objects.all():
        for legacy_scope in credential.scopes or []:
            role_code = LEGACY_SCOPE_ROLES.get(legacy_scope)
            if role_code:
                ApiCredentialRole.objects.get_or_create(
                    credential=credential,
                    role=roles[role_code],
                )


def restore_legacy_scopes(apps, schema_editor):
    ApiCredential = apps.get_model('control', 'ApiCredential')
    reverse_map = {role: scope for scope, role in LEGACY_SCOPE_ROLES.items()}
    for credential in ApiCredential.objects.prefetch_related('access_roles'):
        credential.scopes = sorted(
            {
                reverse_map[role.code]
                for role in credential.access_roles.all()
                if role.code in reverse_map
            }
        )
        credential.save(update_fields=['scopes'])


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_apicredential_scopes_alter_apicredential_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ApiCredentialRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='control.apicredential')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_links', to='control.accessrole')),
            ],
            options={
                'ordering': ('credential__environment', 'credential__name', 'role__code'),
            },
        ),
        migrations.AddField(
            model_name='apicredential',
            name='access_roles',
            field=models.ManyToManyField(blank=True, related_name='credentials', through='control.ApiCredentialRole', to='control.accessrole'),
        ),
        migrations.CreateModel(
            name='ApiScope',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='uq_api_scope_code_ci'), models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='ck_api_scope_code_set')],
            },
        ),
        migrations.CreateModel(
            name='AccessRoleScope',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_links', to='control.accessrole')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_links', to='control.apiscope')),
            ],
            options={
                'ordering': ('role__code', 'scope__code'),
            },
        ),
        migrations.AddField(
            model_name='accessrole',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='access_roles', through='control.AccessRoleScope', to='control.apiscope'),
        ),
        migrations.RunPython(migrate_scopes_to_roles, restore_legacy_scopes),
        migrations.RemoveField(
            model_name='apicredential',
            name='scopes',
        ),
        migrations.CreateModel(
            name='SqlAccessProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], db_index=True, max_length=16)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('environment', 'code'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('environment'), name='uq_sql_access_profile_code_env_ci'), models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='ck_sql_access_profile_code_set')],
            },
        ),
        migrations.CreateModel(
            name='SqlCredentialProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sql_profile_links', to='control.apicredential')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_links', to='control.sqlaccessprofile')),
            ],
            options={
                'ordering': ('credential__environment', 'credential__name', 'profile__code'),
            },
        ),
        migrations.AddField(
            model_name='apicredential',
            name='sql_profiles',
            field=models.ManyToManyField(blank=True, related_name='credentials', through='control.SqlCredentialProfile', to='control.sqlaccessprofile'),
        ),
        migrations.CreateModel(
            name='SqlQueryCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'SQL query category',
                'verbose_name_plural': 'SQL query categories',
                'ordering': ('sort_order', 'name'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='uq_sql_query_category_code_ci'), models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='ck_sql_query_category_code_set')],
            },
        ),
        migrations.CreateModel(
            name='SqlQuery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('kind', models.CharField(choices=[('single', 'Single query'), ('multi_step', 'Multi-step query')], default='single', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sql_queries', to=settings.AUTH_USER_MODEL)),
                ('deprecated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deprecated_queries', to='control.sqlquery')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sql_queries', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queries', to='control.sqlquerycategory')),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='SqlQueryGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('can_execute', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_grants', to='control.sqlaccessprofile')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_grants', to='control.sqlquery')),
            ],
            options={
                'ordering': ('profile__environment', 'profile__code', 'query__key'),
            },
        ),
        migrations.CreateModel(
            name='SqlQueryRevision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=0, editable=False)),
                ('sql_text', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result_description', models.TextField(blank=True)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sql_query_revisions', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='control.sqlquery')),
            ],
            options={
                'ordering': ('query__key', '-revision'),
            },
        ),
        migrations.CreateModel(
            name='SqlQueryPublication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], db_index=True, max_length=16)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('default_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('max_limit', models.PositiveIntegerField(default=100000)),
                ('timeout_seconds', models.PositiveIntegerField(default=120)),
                ('published_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sql_query_publications', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='control.sqlquery')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='control.sqlqueryrevision')),
            ],
            options={
                'ordering': ('environment', 'query__key'),
                'permissions': [('publish_sqlquery', 'Can publish SQL queries')],
            },
        ),
        migrations.CreateModel(
            name='SqlQueryStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_links', to='control.sqlquery')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_links', to='control.sqlquery')),
            ],
            options={
                'ordering': ('parent__key', 'position'),
            },
        ),
        migrations.AddConstraint(
            model_name='apicredentialrole',
            constraint=models.UniqueConstraint(fields=('credential', 'role'), name='uq_api_credential_role'),
        ),
        migrations.AddConstraint(
            model_name='accessrolescope',
            constraint=models.UniqueConstraint(fields=('role', 'scope'), name='uq_access_role_scope'),
        ),
        migrations.AddConstraint(
            model_name='accessrole',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='uq_access_role_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='accessrole',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='ck_access_role_code_set'),
        ),
        migrations.AddConstraint(
            model_name='sqlcredentialprofile',
            constraint=models.UniqueConstraint(fields=('credential', 'profile'), name='uq_sql_credential_profile'),
        ),
        migrations.AddConstraint(
            model_name='sqlquery',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('key'), name='uq_sql_query_key_ci'),
        ),
        migrations.AddConstraint(
            model_name='sqlquery',
            constraint=models.CheckConstraint(condition=models.Q(('key', ''), _negated=True), name='ck_sql_query_key_set'),
        ),
        migrations.AddConstraint(
            model_name='sqlquerygrant',
            constraint=models.UniqueConstraint(fields=('profile', 'query'), name='uq_sql_query_profile_grant'),
        ),
        migrations.AddConstraint(
            model_name='sqlqueryrevision',
            constraint=models.UniqueConstraint(fields=('query', 'revision'), name='uq_sql_query_revision'),
        ),
        migrations.AddConstraint(
            model_name='sqlqueryrevision',
            constraint=models.UniqueConstraint(fields=('query', 'checksum'), name='uq_sql_query_revision_checksum'),
        ),
        migrations.AddConstraint(
            model_name='sqlquerypublication',
            constraint=models.UniqueConstraint(fields=('query', 'environment'), name='uq_sql_query_publication_env'),
        ),
        migrations.AddConstraint(
            model_name='sqlquerypublication',
            constraint=models.CheckConstraint(condition=models.Q(('default_limit__isnull', True), ('default_limit__gt', 0), _connector='OR'), name='ck_sql_publication_default_limit'),
        ),
        migrations.AddConstraint(
            model_name='sqlquerypublication',
            constraint=models.CheckConstraint(condition=models.Q(('max_limit__gt', 0)), name='ck_sql_publication_max_limit'),
        ),
        migrations.AddConstraint(
            model_name='sqlquerypublication',
            constraint=models.CheckConstraint(condition=models.Q(('timeout_seconds__gt', 0)), name='ck_sql_publication_timeout'),
        ),
        migrations.AddConstraint(
            model_name='sqlquerystep',
            constraint=models.UniqueConstraint(fields=('parent', 'position'), name='uq_sql_query_step_position'),
        ),
        migrations.AddConstraint(
            model_name='sqlquerystep',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='uq_sql_query_step_child'),
        ),
        migrations.AddConstraint(
            model_name='sqlquerystep',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='ck_sql_query_step_not_self'),
        ),
        migrations.AddConstraint(
            model_name='sqlquerystep',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='ck_sql_query_step_position'),
        ),
    ]
