# Generated by Django 6.0.8 on 2026-09-04

from django.db import migrations, models


SCOPE_DEFINITIONS = {
    'teams.messages.search': (
        'Search Teams messages',
        'Search messages within the credential Teams policy.',
    ),
    'teams.messages.read': (
        'Read Teams messages',
        'Read Teams messages within the credential Teams policy.',
    ),
    'teams.attachments.read': (
        'Read Teams attachments',
        'Read Teams attachments within the credential Teams policy.',
    ),
}


def create_teams_access_role(apps, schema_editor):
    ApiScope = apps.get_model('control', 'ApiScope')
    AccessRole = apps.get_model('control', 'AccessRole')
    AccessRoleScope = apps.get_model('control', 'AccessRoleScope')

    scopes = {}
    for code, (name, description) in SCOPE_DEFINITIONS.items():
        scope, _created = ApiScope.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'description': description,
                'is_active': True,
            },
        )
        scopes[code] = scope

    role, _created = AccessRole.objects.update_or_create(
        code='teams-agent',
        defaults={
            'name': 'Teams agent',
            'description': 'Standard access role for the Teams Graph API.',
            'is_active': True,
        },
    )
    for scope in scopes.values():
        AccessRoleScope.objects.get_or_create(role=role, scope=scope)


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_accessrole_remove_apicredential_scopes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='policy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(
            create_teams_access_role,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
